//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURCE_INFO
    {
        public int ID { get; set; }
        public string COURCE_CODE { get; set; }
        public string COURCE_TITLE { get; set; }
        public string SESSION_NO { get; set; }
    }
}
