//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_MARK
    {
        public int ROLL { get; set; }
        public string NAME { get; set; }
        public double CT1 { get; set; }
        public double CT2 { get; set; }
        public double CT3 { get; set; }
        public int AVARAGE_MARK { get; set; }
        public int ATTENDENCE_MARK { get; set; }
        public int TOTAL { get; set; }
    }
}
